apiVersion: v1
kind: ConfigMap
metadata:
  name: configmappgadmin
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: pgadmin
data:
   servers.json: |
     {
       "Servers": {
         "1": {
           "Name": "adyd",
           "Group": "adyd servers",
           "Port": 5432,
           "Username": "adydadmin",
           "Host": "stateful-db.adyd",
           "MaintenanceDB": "postgres"
         }
       }
     }
    