apiVersion: v1
kind: Secret
metadata:
  name: config-secret
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: configserver
type: Opaque
data:
  bbdduser: YWR5ZGFkbWlu
  bbddpassword: cGFzczRhZG1pbg==   
  keypass: cGFzc3dvcmQ=