apiVersion: apps/v1
kind: Deployment
metadata:
  name: adydtablas
  namespace: adyd
  labels:
    environment: desarrollo
    app: adydtablas
spec:  
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: adydtablas
  template:
    metadata:
      labels:
        app: adydtablas
    spec:
      containers:
      - name: adydtablas
        image: gilmith/adydtablas:0.0.2
        ports:
        - containerPort: 10004
        env:
        - name: URLCONFIG
          valueFrom:
            configMapKeyRef:
              name: cmconfigserver
              key: URLCONFIG
