apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: adyd
  labels:
    environment: desarrollo
    app: apigateway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: gilmith/apigateway:0.0.4
        ports:
        - containerPort: 10003