apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailservice
  namespace: adyd
  labels:
    environment: desarrollo
    app: mailservice
spec:  
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: mailservice
  template:
    metadata:
      labels:
        app: mailservice
    spec:
      containers:
      - name: mailservice
        image: gilmith/mailservice:0.0.9
        ports:
        - containerPort: 10003
        env:
        - name: URLCONFIG
          valueFrom:
            configMapKeyRef:
              name: cmconfigserver
              key: URLCONFIG
