apiVersion: apps/v1
kind: Deployment
metadata:
  name: adyddb
  namespace: adyd
  labels:
    environment: desarrollo
    app: postgree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgree
  template:
    metadata:
      labels:
        app: postgree
    spec:
      containers:
      - name: postgres
        image: gilmith/adyd3:0.0.14
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-x", "/createdatabase/00_init-user-db.sh"]
          preStop:
            exec:
              command: ["echo", "Adios"]
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: configmap1
              key: POSTGRES_DB   
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: configmap1
              key: POSTGRES_USER                     
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: rootpassword
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: pgdata
        - mountPath : "/tablasjuego"
          name: tablas
        - mountPath: "/config"
          name: config
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: config-bbdd-claim
      - name: tablas
        persistentVolumeClaim:
          claimName: tablasjuego-bbdd-claim
      - name: config
        persistentVolumeClaim:
          claimName: configserver-bbdd-claim
      
      
