apiVersion: apps/v1
kind: Deployment
metadata:
  name: verdaccio
  namespace: adyd
  labels:
    environment: desarrollo
    app: verdaccio
spec:  
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: verdaccio
  template:
    metadata:
      labels:
        app: verdaccio
    spec:
      containers:
      - name: verdaccio
        image: verdaccio/verdaccio
        ports:
        - containerPort: 4873
