apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: adyd
  labels:
    environment: desarrollo
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4        
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: configmap1
              key: PGADMIN_DEFAULT_EMAIL                          
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: pgadminpasswd