apiVersion: v1
kind: Service
metadata:
  name: servicepgadmin
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: pgadmin
spec:
  selector:
    app: pgadmin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      
