apiVersion: v1
kind: Service
metadata:
  name: servicezipkin
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: zipkin
spec:
  selector:
    app: zipkin
  type: NodePort
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30003
      
