apiVersion: v1
kind: Service
metadata:
  name: servicemail
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: mailservice
spec:
  selector:
    app: mailservice
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10003
      targetPort: 10003
      #nodePort: 30002
      
