apiVersion: v1
kind: Service
metadata:
  name: servicefront
  namespace: adyd
  labels:
    enviorment: produccion
    app: frontservice
spec:
  selector:
    app: frontservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 30002
      
