apiVersion: v1
kind: Service
metadata:
  name: serviceeureka
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: eurekaadyd
spec:
  selector:
    app: eurekaadyd
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      
