apiVersion: v1
kind: Service
metadata:
  name: servicelogin
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: loginadyd
spec:
  selector:
    app: loginadyd
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10002
      targetPort: 10002
      
