apiVersion: v1
kind: Service
metadata:
  name: servicelogin
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: adydtablas
spec:
  selector:
    app: adydtablas
  type: NodePort
  ports:
    - protocol: TCP
      port: 10004
      targetPort: 10004
      
