apiVersion: v1
kind: Service
metadata:
  name: servicebbddadyd
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: postgree
spec:
  selector:
    app: postgree
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30002
      
