apiVersion: v1
kind: Service
metadata:
  name: serviceverdaccio
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: verdaccio
spec:
  selector:
    app: verdaccio
  type: NodePort
  ports:
    - protocol: TCP
      port: 4873
      targetPort: 4873
      nodePort: 30004
      
