apiVersion: v1
kind: Service
metadata:
  name: serviceconfigserver
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: configserver
spec:
  selector:
    app: configserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 10001
      nodePort: 30002      
