apiVersion: v1
kind: Service
metadata:
  name: servicegateway
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: apigateway
spec:
  selector:
    app: apigateway
  type: NodePort
  ports:
    - protocol: TCP
      port: 10003
      targetPort: 10003
      
