apiVersion: v1
kind: LimitRange
metadata:
  name: limits-prueba
  namespace: adyd
  labels:
    enviorment: desarrollo
    app: bbdd
spec:
  limits:
  - default:
      memory: "512Mi"
      cpu: "750m"
    defaultRequest:
      memory: "256Mi"
      cpu: "500m"
    max:
      memory: "1Gi"
      cpu: "1"
    min:
      memory: "64Mi"
      cpu: "250m"
    type: Container
