apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adydmongosfs
  namespace: adyd
  labels:
    environment: desarrollo
    app: mongodb
spec:
  serviceName: mongostateful-db
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: gilmith/mongoadyd:0.0.1
        ports:
        - containerPort: 27017        

      
