apiVersion: v1
kind: Service
metadata:
  name: mognodbst-db
  namespace: adyd
  labels:
    environment: desarrollo
    app: mongodb
spec:
  ports:
    - port: 21017
      name: mongodb
  clusterIP: None
  selector:
    app: mongodb